spring:
  application:
    name: greeting-service
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
greeting-service:
<<<<<<< HEAD
  greeting: "Pronto"
=======
  greeting: "Ciao"
>>>>>>> a796af5abbce799d84475e08c9c25ce44d88a63e
  default-value: "Mondo"
